config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        post '/representatives/:representative_id/my_news_item/search' => 'my_news_items#search',
            :as                                                       => :search_my_news_item
        post '/representatives/:representative_id/my_news_item/new' => 'my_news_items#create',
            :as                                                    => :create_my_news_item
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'

    resources :campaigns
    get '/campaignfinance', to: 'campaigns#index', :as => 'campaign_finance'
    post '/campaignfinance', to: 'campaigns#search', :as => 'search_campaign_finance'
end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list
  before_action :set_issues_list
  before_action :set_news_item, only: %i[edit update destroy]

  def new
    @news_item = NewsItem.new
  end

  def search
    @representative = Representative.find(params[:representative_id])
    @issue = params[:news_item][:issue]
    # Call News API to get articles
    query = "#{@representative.name} #{@issue}"
    @articles = fetch_news_articles(query)

    render 'search'
  end

  def create
    @news_item = NewsItem.new(news_item_params)
    if @news_item.save
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def edit; end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  def set_issues_list
    @issues_list = ['Free Speech', 'Immigration', 'Terrorism', 'Social Security and
    Medicare', 'Abortion', 'Student Loans', 'Gun Control', 'Unemployment',
                    'Climate Change', 'Homelessness', 'Racism', 'Tax Reform', 'Net
    Neutrality', 'Religious Freedom', 'Border Security', 'Minimum Wage',
                    'Equal Pay']
  end

  def fetch_news_articles(query)
    api_key = Rails.application.credentials[:GOOGLE_NEWS_API_KEY]
    url = "https://newsapi.org/v2/everything?q=#{CGI.escape(query)}&apiKey=#{api_key}&pageSize=5"
    response = Faraday.get(url)
    json = JSON.parse(response.body)
    articles = []
    json['articles'].each do |article|
      title = article['title']
      link = article['url']
      description = article['description']
      articles.append({ title: title, link: link, description: description })
    end
    articles
  rescue StandardError => e
    Rails.logger.error("News API error: #{e.message}")
    []
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id, :issue)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: false },
            class: 'form-control'
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
         form_url: representative_edit_my_news_item_path(@representative, @news_item),
         form_method: :put,
         representatives_list: @representatives_list,
         issues_list: @issues_list
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_item_path(@news_item), class: 'mx-1 btn btn-info' do
                    Show article
                    %i.fas.fa-eye
                = link_to representative_news_items_path(@representative), class: 'mx-1 btn btn-info' do
                    View all news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Find News Articles

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_for :news_item, url: representative_search_my_news_item_path(@representative), method: :post do |f|
            .form-group.row
                .col-sm-3
                    = label :news_item, :representative_id, class: 'col-form-label'
                .col-sm-13
                    = select :news_item, :representative_id, @representatives_list, { include_blank: true },
                    class: 'form-control'

            .form-group.row
                .col-sm-2
                    = label :news_item, :issue, class: 'col-form-label'
                .col-sm-13
                    = select :news_item, :issue, @issues_list, { include_blank: false },
                    class: 'form-control'

            .actions
                = f.submit 'Search Articles', class: 'btn btn-primary'

app/views/my_news_items/search.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Select News Article
        .card.mb-4
            .card-body
                %h5.card-title Representative Information
                %p.mb-1
                    %strong Representative:
                    = @representative.name
                %p.mb-0
                    %strong Issue:
                    = @issue
        = form_for :news_item, url: representative_create_my_news_item_path(@representative), method: :post do |f|
            .form-group
                - @articles.each do |article|
                    .card.mb-3
                        .card-body
                            .form-check
                                = radio_button_tag 'news_item[title]', article[:title], false,
                                class: 'form-check-input',
                                data: { link: article[:link], description: article[:description] }
                        .card-body.d-flex.justify-content-end
                        %h5.card-title= article[:title]
                        %p.card-text
                            %strong Link:
                            = link_to article[:link], article[:link], target: '_blank', rel: 'noopener'
                        %p.card-text
                            %strong Description:
                            = article[:description]
            = hidden_field_tag 'news_item[representative_id]', @representative.id
            = hidden_field_tag 'news_item[issue]', @issue
            = hidden_field_tag 'news_item[link]', '', id: 'news_item_link'
            = hidden_field_tag 'news_item[description]', '', id: 'news_item_description'
            .form-group
                = label_tag :rating, 'Rate this article (1-5):'
                = select_tag 'news_item[rating]', options_for_select(1..5), class: 'form-control'
            .actions
                = f.submit 'Save', class: 'btn btn-primary'

:javascript
    document.addEventListener('DOMContentLoaded', function() {
        const radioButtons = document.querySelectorAll('input[name="news_item[title]"]');
        radioButtons.forEach(radio => {
            radio.addEventListener('change', function() {
                const selectedLink = this.dataset.link;
                const selectedDescription = this.dataset.description;
                document.getElementById('news_item_link').value = selectedLink;
                document.getElementById('news_item_description').value = selectedDescription;
            });
        });
    });